### ISSUE TITLE
The Google Drive node does not report status when uploading

### ISSUE THREAD

**Issue by kdo-sw** [Agile-IoT/node-red-contrib-agile-googledrive#4]
There is no way to know if a file upload was successful or not, which can be the case if there for some reason is no network connection. This prevents cleaning up the local files, because the application never knows when the data has arrived to the cloud.

**Comment by brettdaman** [comment]
This is by design. @rosogon  described the component in https://github.com/Agile-IoT/Architecture/issues/5

> Output
> The node is a regular output node and MUST NOT provide input to other nodes. This way, it behaves as the stock File node.

**Comment by rosogon** [comment]
According to https://nodered.org/docs/creating-nodes/status:

> From Node-RED v0.12.x the Status node can be used to catch any node status updates, for example connect and disconnect messages, in order to trigger other flows.

The Status node sends:
* text: message shown to the user (to be used to detect errors)
* source.type: type of node updating status
* source.id: id of node updating status
* source.name: name of node updating status

@kdo-sw, do you think the Status node is enough for your needs?

@brettdaman, in your current implementation, could you prepare a list of possible status (including success)? To check if they can be normalized between different implementations.

**Comment by brettdaman** [comment]
v1.0.2 has an output for status updates.
Please verify if this is sufficient for your use case
